name: Deploy to Azure app service

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Node.js Version
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Install Dependencies
        run: npm install
      - name: "Create env file"
        run: |
          touch .env
          echo Database_URL = mongodb://localhost:27017 >> .env
          echo SMTP_EMAIL = mahobiashubham4@gmail.com >> .env
          echo SMTP_HOST = smtp.gmail.com >> .env
          echo SMTP_PASS = hutufymgqfwvnzdh >> .env
          echo JWT_TOKEN_EXPIRY = 24h >> .env
          echo SECRET_KEY = 81012BB9A64888F4A27786E63DF9B5A65DBD04398402026F67D3B2525DFEDB2E >> .env
          cat .env
      - name: Running Node Application
        run: node index.js
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: rideEye
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
